language: objective-c
os: osx
osx_image: xcode9.2

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=CBPopupExample.xcodeproj
    - CONFIG=Release
    - ACTION="build-for-testing test-without-building"

 matrix:
    - SCHEME="CBPopupExample"

branches:
  only: 
    - master

before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - set -o pipefail
  - xcodebuild $ACTION -project $PROJECT -scheme $SCHEME -sdk $SDK -destination 'name=iPhone 7,OS=11.2' -configuration $CONFIG ENABLE_TESTABILITY=YES | xcpretty

notifications:
  email: false
